<img src='tensor.png'>

<img src='parcs.png'>

In [8]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [9]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [10]:
train_images.shape

(60000, 28, 28)

In [11]:
len(train_labels)

60000

In [12]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [13]:
test_images.shape

(10000, 28, 28)

In [14]:
len(test_labels)

10000

In [15]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [16]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [36]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(50, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_2 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 128)               100480    
_________________________________________________________________
dense_5 (Dense)              (None, 50)                6450      
_________________________________________________________________
dense_6 (Dense)              (None, 10)                510       
Total params: 107,440
Trainable params: 107,440
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [38]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.6680 - accuracy: 0.7705
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3824 - accuracy: 0.8582
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3394 - accuracy: 0.8756
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3094 - accuracy: 0.8856
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2899 - accuracy: 0.8935


In [39]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

313/313 [==============================] - 0s 787us/step - loss: 0.3321 - accuracy: 0.8808
Test accuracy: 0.8808000087738037


In [40]:
predictions = model.predict(test_images)

In [41]:
predictions[0]

array([4.0999184e-06, 4.3698965e-06, 1.9814020e-06, 3.8243916e-06,
       2.4232455e-05, 1.2218258e-02, 4.0366263e-05, 1.8480865e-02,
       4.3496124e-07, 9.6922159e-01], dtype=float32)

In [42]:
np.argmax(predictions[0])

9

In [43]:
test_labels[0]

9

In [44]:
img = test_images[0]

print(img.shape)

(28, 28)


In [45]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [46]:
predictions_single = model.predict(img)

print(predictions_single)

[[4.0999184e-06 4.3699047e-06 1.9814038e-06 3.8243952e-06 2.4232477e-05
  1.2218253e-02 4.0366340e-05 1.8480884e-02 4.3496206e-07 9.6922159e-01]]


In [47]:
np.argmax(predictions_single[0])

9